@base_url = http://localhost:8080

@userId = 689e1f72-a536-48f8-a9e4-0ed4986bf2b2

@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3YjBlODA0Yi03MjkyLTRiYzAtODQzNy0yYzY3MjYzMTliNjgiLCJlbWFpbCI6InRlc3Q0QGV4YW1wbGUuY29tIiwibmlja05hbWUiOiLtmY3quLjrj5kiLCJ1c2VyUm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcyOTc1NDA4NywiaWF0IjoxNzI5NzUwNDg3fQ.au3OGOdfh4Ki-1pwYBX15DFssPnodW-jjPLqdKs6t3o

@expired_jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2ODllMWY3Mi1hNTM2LTQ4ZjgtYTllNC0wZWQ0OTg2YmYyYjIiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJuaWNrTmFtZSI6Iu2Zjeq4uOuPmSIsInVzZXJSb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI5Njg5ODcyLCJpYXQiOjE3Mjk2ODYyNzJ9.g9lz3Ou3XcJ9leE0iuw9ohoHftskYFwLrSFyL1VIysY

### 회원가입 요청
POST {{base_url}}/api/users/signup
Content-Type: application/json

{
  "email": "test4@example.com",
  "nickName": "홍길동",
  "password": "password123",
  "identityProvider": "NONE"
}


### 일반 로그인 요청
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
  "email": "test4@example.com",
  "password": "password123"
}

### 회원탈퇴 요청
PATCH {{base_url}}/api/users/{{userId}}
Authorization: Bearer {{jwt_token}}
Content-Type: application/json


### 회원탈퇴 요청 (JWT 토큰 만료)
PATCH {{base_url}}/api/users/me/delete
Authorization: Bearer {{expired_jwt}}
Content-Type: application/json


### Refresh Token을 통한 Access Token 재발급 요청
POST {{base_url}}/api/auth/token/refresh
Content-Type: application/json

{
  "refresh_token": ""
}

### 카테고리 생성
POST {{base_url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "categoryName": "공부"
}

### 카테고리 조회
GET {{base_url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### 카테고리 수정
PUT {{base_url}}/api/categories/9b0bdb8b-9a90-4579-aac9-862a4d18cb15
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "categoryName": "여가"
}


### 카테고리 삭제
PATCH {{base_url}}/api/categories/32aeabed-65c5-4978-a1c7-d2e3c9524381
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### 모임 생성
POST {{base_url}}/api/gathers
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "즐거운 풋살모임"
}

### 멤버 생성
POST {{base_url}}/api/members/user/7b0e804b-7292-4bc0-8437-2c6726319b68/gather/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
}

### 멤버 승인
PATCH {{base_url}}/api/members/2/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
}


### 해시태그 생성
POST {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "hashTagName": "풋살2"
}


### 해시태그 조회
GET {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}

### 해시태그 삭제
PATCH {{base_url}}/api/gatherings/{gatherId}/hashtags/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{

}





