@base_url = http://localhost:8080

@user_Id = 4245716d-9ed2-439c-a2f0-a83b87facd9e

@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMDUyMGM4ZC1hYzFmLTRhNDAtOGJjMC03MGU0Mjg1NGE1MzIiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJ1c2VyUm9sZSI6IlJPTEVfQURNSU4iLCJpYXQiOjE3MzA0MDE2NzIsImV4cCI6MTczMDQwMzQ3Mn0.WgD_p0BLUlR8_-aOCWgtTY2hloGtEBhc8Zzx2nIqf0g

@expired_jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MjQ1NzE2ZC05ZWQyLTQzOWMtYTJmMC1hODNiODdmYWNkOWUiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJ1c2VyUm9sZSI6IlJPTEVfQURNSU4iLCJpYXQiOjE3MzAzNzI5OTksImV4cCI6MTczMDM3NDc5OX0.xlYiDp2ewoYVsAuRNPrKgk8WPUSwGDRvrNM1swZcgpg

@memberId = 2

@category_Id = 1

@gatherId = 2

### 회원가입 요청
POST {{base_url}}/api/users/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "nickName": "홍길동",
  "password": "password123A!",
  "identityProvider": "NONE"
}


### 일반 로그인 요청
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123A!"
}

### 비밀번호 변경
PATCH {{base_url}}/api/users/me/password
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "oldPassword": "password123A!",
  "newPassword": "password123A!"
}

### 닉네임 변경
PATCH {{base_url}}/api/users/me/nickname
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "newNickName": "홍길동"
}

### 내 프로필 조회
GET {{base_url}}/api/users/me/profile
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 회원탈퇴 요청
PATCH {{base_url}}/api/users/me/delete
Authorization: Bearer {{jwt_token}}
Content-Type: application/json


### 회원탈퇴 요청 (JWT 토큰 만료)
PATCH {{base_url}}/api/users/me/delete
Authorization: Bearer {{expired_jwt}}
Content-Type: application/json


### 카테고리 생성
POST {{base_url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "categoryName": "공부"
}

### 카테고리 조회
GET {{base_url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 카테고리 수정
PUT {{base_url}}/api/categories/{{category_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "categoryName": "여가"
}


### 카테고리 삭제
PATCH {{base_url}}/api/categories/{{category_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 모임 생성
POST {{base_url}}/api/gathers/{{category_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "즐거운 풋살모임",
  "description": "type: string",
  "hashtags": [
    "list로",
    "받습니다."
  ]
}

### 멤버 생성
POST {{base_url}}/api/members/user/{{user_Id}}/gather/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 멤버 승인
PATCH {{base_url}}/api/members/{{memberId}}/gather/{{gatherId}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 멤버 가입 거절
PATCH {{base_url}}/api/members/{{memberId}}/gather/{{gatherId}}/refusal
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 모임 탈퇴
PATCH {{base_url}}/api/members/{{memberId}}/withdrawl
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 해시태그 생성
POST {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "hashTagName": [
    "풋살",
    "운동"
  ]
}


### 해시태그 조회
GET {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 해시태그 삭제
PATCH {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 이미지 등록
POST {{base_url}}/api/users/{{user_Id}}/profile-image
Content-Type: multipart/form-data
Authorization: Bearer {{jwt_token}}

{
"file": https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1QoiaHL8SAnH1qLQmbN4Ba06h8RYXZfh8Ow&s
}

### 보드 생성
POST {{base_url}}/api/gather/1/boards
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "boardTitle": "보드 타이틀",
  "boardContent": "보드 컨텐츠"
}

### 댓글생성
POST {{base_url}}/api/schedule/1/comments
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "comment": "보드 타이틀3"
}

### 댓글조회
GET {{base_url}}/api/schedule/1/comments
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "comment": "보드 타이틀3"
}


### 댓글수정
PATCH {{base_url}}/api/schedule/1/comments/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "comment": "보드 수정"
}


### 댓글삭제
PATCH {{base_url}}/api/schedule/1/comments/3/delete
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
}


### 지도검색
GET {{base_url}}/api/kakaoMap
Content-Type: application/json

{
  "address": "인천 석남1동"
}


### 지도저장
POST {{base_url}}/api/kakaoMap
Content-Type: application/json

{
  "address": "인천 석남동"
}










