@base_url = http://localhost:8080

@user_Id = eee86d4d-4990-4ec4-aa8b-05afd4314ebe

@category_Id = ae7787ca-f3f0-450f-8c92-c2e36f02941b

@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMTNlOTJiYi1jMTYzLTQ3NzctYmJlMi04YTFjYjdlYWNiYmYiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzMwMjA5NDMyLCJpYXQiOjE3MzAyMDU4MzJ9.1KRXplayN1f-AKY9KUDh0Lso2JasBTZa0FBuvj3nfQo

@expired_jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2ODllMWY3Mi1hNTM2LTQ4ZjgtYTllNC0wZWQ0OTg2YmYyYjIiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJuaWNrTmFtZSI6Iu2Zjeq4uOuPmSIsInVzZXJSb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI5Njg5ODcyLCJpYXQiOjE3Mjk2ODYyNzJ9.g9lz3Ou3XcJ9leE0iuw9ohoHftskYFwLrSFyL1VIysY

### 회원가입 요청
POST {{base_url}}/api/users/signup
Content-Type: application/json

{
  "email": "test1@example.com",
  "nickName": "홍길동",
  "password": "password123",
  "identityProvider": "NONE"
}

### 회원가입 요청
POST {{base_url}}/api/users/signup
Content-Type: application/json

{
  "email": "test2@example.com",
  "nickName": "김철수",
  "password": "password123",
  "identityProvider": "NONE"
}

### 일반 로그인 요청
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "password123"
}

### 회원탈퇴 요청
PATCH {{base_url}}/api/users/me/delete
Authorization: Bearer {{jwt_token}}
Content-Type: application/json


### 회원탈퇴 요청 (JWT 토큰 만료)
PATCH {{base_url}}/api/users/me/delete
Authorization: Bearer {{expired_jwt}}
Content-Type: application/json

### 카테고리 생성
POST {{base_url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "categoryName": "공부"
}

### 카테고리 조회
GET {{base_url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 카테고리 수정
PUT {{base_url}}/api/categories/{{user_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "categoryName": "여가"
}


### 카테고리 삭제
PATCH {{base_url}}/api/categories/{{user_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 모임 생성
POST {{base_url}}/api/gathers/{{category_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "풋살",
  "description": "할래",
  "hashtags": [
    "축구할사람"
  ]
}

### 멤버 생성
POST {{base_url}}/api/members/user/{{user_Id}}/gather/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 멤버 승인
PATCH {{base_url}}/api/members/2/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 해시태그 생성
POST {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "hashTagName": [
    "축구사랑하는분"
  ]
}


### 해시태그 조회
GET {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 해시태그 삭제
PATCH {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 이미지 등록
POST {{base_url}}/api/users/{{user_Id}}/profile-image
Content-Type: multipart/form-data
Authorization: Bearer {{jwt_token}}

{
  "file": https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1QoiaHL8SAnH1qLQmbN4Ba06h8RYXZfh8Ow&s"
}

### 스케쥴 생성
POST {{base_url}}/api/gather/1/schedule
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "scheduleTitle": "스케쥴 타이틀",
  "scheduleContent": "스케쥴 컨텐츠"
}

### 보드 생성
POST {{base_url}}/api/gather/1/boards
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "boardTitle": "보드 타이틀",
  "boardContent": "보드 컨텐츠"
}





