@base_url = http://localhost:8080

@user_Id = 4245716d-9ed2-439c-a2f0-a83b87facd9e

@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3MjM1OTMxMi01YjljLTQ4ZjAtYmNjNC0zOWU0ZWUxYTJkYWQiLCJlbWFpbCI6Im5iY3RlYW0yMXRlc3RAZ21haWwuY29tIiwidXNlclJvbGUiOiJST0xFX0FETUlOIiwiaWF0IjoxNzMxOTIwOTkyLCJleHAiOjE3MzE5MjI3OTJ9.i3epid073V5P7zJhvV6fMysKHB819XH5IwEvrsYdUyI

@expired_jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MjQ1NzE2ZC05ZWQyLTQzOWMtYTJmMC1hODNiODdmYWNkOWUiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJ1c2VyUm9sZSI6IlJPTEVfQURNSU4iLCJpYXQiOjE3MzAzNzI5OTksImV4cCI6MTczMDM3NDc5OX0.xlYiDp2ewoYVsAuRNPrKgk8WPUSwGDRvrNM1swZcgpg

@refresh_token =eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhMTM3ZmRhZS02OTI4LTQ1N2EtOTBlMi01YTU0NjI4YmYxZWYiLCJpYXQiOjE3MzE4NzcwNTcsImV4cCI6MTczMTk2MzQ1N30.UNQ3HBHl6Zkt-ih-htR5_v_M2SCRsm6Mdq0A_eQusso

@expired_refresh_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhMTM3ZmRhZS02OTI4LTQ1N2EtOTBlMi01YTU0NjI4YmYxZWYiLCJpYXQiOjE3MzE4NzY1NzEsImV4cCI6MTczMTk2Mjk3MX0.y69UiHYx80syBZjgIieJtrOp-ckzRS0PzQJChDwKBWw

@memberId = 1

@category_Id = 1

@gatherId = 1

@agreement_Id = 17a980dd-a53e-11ef-9770-00155dbf39e6

### 약관 생성 테스트
### PRIVACY_POLICY = 개인정보 처리방침
### TERMS_OF_SERVICE = 서비스 이용약관
### MARKETING_INFO_RECEIVE_AGREEMENT = 마케팅 정보 수신 동의
POST{{base_url}}/api/agreements
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "content": "약관 내용입니다.",
  "version": "1.0",
  "type": "PRIVACY_POLICY"
}

### 약관 수정 테스트
PATCH {{base_url}}/api/agreements/update/{{agreement_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "content": "수정된 이용약관 내용입니다89",
  "version": "8.9"
}

### 타입별 약관 조회 테스트
GET {{base_url}}/api/agreements/latest?type=PRIVACY_POLICY
Accept: application/json

### 모든 약관 조회 테스트
GET {{base_url}}/api/agreements/latest/all
Accept: application/json

### 이메일 인증 코드 발송 요청
POST {{base_url}}/api/verification/send
Content-Type: application/json

{
  "email": "nbcteam21test@gmail.com"
}

### 인증 코드 확인 요청
POST {{base_url}}/api/verification/confirm
Content-Type: application/json

{
  "email": "nbcteam21test@gmail.com",
  "code": "393755"
}

### Agreement Expiration Job 실행 요청
POST {{base_url}}/api/batch/runAgreementExpiration
Content-Type: application/json

### 회원가입 요청 - 약관 통합
POST {{base_url}}/api/users/signup
Content-Type: application/json

{
  "email": "",
  "nickName": "",
  "password": "",
  "identityProvider": "NONE",
  "agreedAgreementIds": [
    "17a980dd-a53e-11ef-9770-00155dbf39e6",
    "17a9833c-a53e-11ef-9770-00155dbf39e6",
    "17a983d8-a53e-11ef-9770-00155dbf39e6"
  ]
}

### 회원가입 요청 - 약관 통합
POST {{base_url}}/api/users/signup
Content-Type: application/json

{
  "email": "nbcteam21test@gmail.com",
  "nickName": "홍길동",
  "password": "password123A!",
  "identityProvider": "NONE",
  "agreedAgreementIds": [
    "4c2b7d86-0f48-448e-949a-fc37557cc983",
    "2f95fb4c-5ce1-493f-afc8-428b694cf299"
  ]
}

### 일반 로그인 요청
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
  "email": "nbcteam21test@gmail.com",
  "password": "password123A!"
}

### 리프레시 토큰으로 액세스 토큰 재발급
POST {{base_url}}/api/auth/refresh-token
Content-Type: application/json
Cookie: refreshToken={{refresh_token}}

### 만료된 리프레시 토큰으로 재발급 요청
POST {{base_url}}/api/auth/refresh-token
Content-Type: application/json
Cookie: refreshToken={{expired_refresh_token}}

### 로그아웃 요청 (리프레시 토큰 삭제)
POST {{base_url}}/api/auth/logout
Content-Type: application/json
Cookie: refreshToken={{refresh_token}}

### 비밀번호 변경
PATCH {{base_url}}/api/users/me/password
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "oldPassword": "password123A!",
  "newPassword": "password123A!"
}

### 닉네임 변경
PATCH {{base_url}}/api/users/me/nickname
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "newNickName": "홍길동"
}

### 내 프로필 조회
GET {{base_url}}/api/users/me/profile
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 회원탈퇴 요청
PATCH {{base_url}}/api/users/me/delete
Authorization: Bearer {{jwt_token}}
Content-Type: application/json
Cookie: refreshToken={{refresh_token}}

### 회원탈퇴 요청 (JWT 토큰 만료)
PATCH {{base_url}}/api/users/me/delete
Authorization: Bearer {{expired_jwt}}
Content-Type: application/json


### 카테고리 생성
POST {{base_url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "categoryName": "영화"
}

### 카테고리 조회
GET {{base_url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 카테고리 수정
PUT {{base_url}}/api/categories/{{category_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "categoryName": "여가"
}


### 카테고리 삭제
PATCH {{base_url}}/api/categories/{{category_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 모임 생성
POST {{base_url}}/api/gathers/{{category_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "강릉-",
  "description": "같이 공차실분",
  "hashtags": [
    "여의도공원",
    "저녁",
    "실외"
  ],
  "addressName": "서울 동작구 노량진로 111",
  "latitude": 37.7645195812136,
  "longitude": 128.899617238918
}

### 모임 수정
PUT {{base_url}}/api/gathers/{{gatherId}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "농구하실분",
  "description": "여의도 공원 농구 모임",
  "hashtags": [
    "여의도공원",
    "저녁",
    "실외"
  ],
  "addressName": "서울 영등포구 여의도동 여의공원로 68",
  "latitude": "37.5134034035131",
  "longitude": "126.943292835393"
}

### 모임 삭제
PATCH  {{base_url}}/api/gathers/{{gatherId}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 카테고리별 모임 검색
GET {{base_url}}/api/gathers/{{category_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### hashTag 검색
GET {{base_url}}/api/gathers/search?hashTagName=20대&hashTagName=건강&page=1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### title 검색
GET {{base_url}}/api/gathers/title?title=즐거운&page=1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 동네 조회
GET {{base_url}}/api/gathers/topRanking
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 모임 상세페이지
GET {{base_url}}/api/gathers/{{gatherId}}/detail
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 멤버 생성
POST {{base_url}}/api/members/user/{{user_Id}}/gather/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 멤버 승인
PATCH {{base_url}}/api/members/{{memberId}}/gather/{{gatherId}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 멤버 가입 거절
PATCH {{base_url}}/api/members/{{memberId}}/gather/{{gatherId}}/refusal
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 모임 탈퇴
PATCH {{base_url}}/api/members/{{memberId}}/withdrawl
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 해시태그 생성
POST {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "hashTagName": [
    "영화 모임"
  ]
}


### 해시태그 조회
GET {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### 해시태그 삭제
PATCH {{base_url}}/api/gatherings/1/hashtags
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 이미지 등록
POST {{base_url}}/api/users/{{user_Id}}/profile-image
Content-Type: multipart/form-data
Authorization: Bearer {{jwt_token}}

{
"file": https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1QoiaHL8SAnH1qLQmbN4Ba06h8RYXZfh8Ow&s
}

### 보드 생성
POST {{base_url}}/api/gather/1/boards
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "boardTitle": "보드2",
  "boardContent": "보드2 컨텐츠"
}

### 스케쥴 생성
POST {{base_url}}/api/gather/1/schedule
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "scheduleTitle": "스케쥴2",
  "scheduleContent": "스케쥴2 컨텐츠"
}



### 댓글생성
POST {{base_url}}/api/schedule/1/comments
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "comment": "보드 타이틀3"
}

### 댓글조회
GET {{base_url}}/api/schedule/1/comments
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "comment": "보드 타이틀3"
}


### 댓글수정
PATCH {{base_url}}/api/schedule/1/comments/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "comment": "보드 수정"
}


### 댓글삭제
PATCH {{base_url}}/api/schedule/1/comments/3/delete
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
}


### 지도검색
GET {{base_url}}/api/kakaoMap
Content-Type: application/json

{
  "address": "강원특별자치도 강릉시 용지로 176"
}

### 지도저장
POST {{base_url}}/api/kakaoMap/2
Content-Type: application/json

{
  "address": "인천 석남1동"
}

### 지도조회(래디스)
GET {{base_url}}/api/kakaoMap/RedisSearch
Content-Type: application/json

{
  "latitude": "37.51340296744142",
  "longitude": "126.94329053163528",
  "distance": 175
}


### 쿠폰 요청
POST {{base_url}}/api/coupons/request
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


### 쿠폰 조회
GET {{base_url}}/api/coupons/status
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


