@base_url = http://localhost:8080

@user_Id = 4245716d-9ed2-439c-a2f0-a83b87facd9e

@jwt_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmNjBiODFhYy1iMjIzLTQzNDAtYmU4Yi0yODYyMWJmMTRiZTciLCJlbWFpbCI6Im5iY3RlYW0yMXRlc3RAZ21haWwuY29tIiwidXNlclJvbGUiOiJST0xFX0FETUlOIiwiaWF0IjoxNzMzODI0NzY3LCJleHAiOjE3MzM4MjY1Njd9.fGi6foDnZ90qrQUkhcchk4m551HW4tmF5LC_CHJ0y3o

@expired_jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MjQ1NzE2ZC05ZWQyLTQzOWMtYTJmMC1hODNiODdmYWNkOWUiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJ1c2VyUm9sZSI6IlJPTEVfQURNSU4iLCJpYXQiOjE3MzAzNzI5OTksImV4cCI6MTczMDM3NDc5OX0.xlYiDp2ewoYVsAuRNPrKgk8WPUSwGDRvrNM1swZcgpg

@refresh_token =eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhMTM3ZmRhZS02OTI4LTQ1N2EtOTBlMi01YTU0NjI4YmYxZWYiLCJpYXQiOjE3MzE4NzcwNTcsImV4cCI6MTczMTk2MzQ1N30.UNQ3HBHl6Zkt-ih-htR5_v_M2SCRsm6Mdq0A_eQusso

@expired_refresh_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhMTM3ZmRhZS02OTI4LTQ1N2EtOTBlMi01YTU0NjI4YmYxZWYiLCJpYXQiOjE3MzE4NzY1NzEsImV4cCI6MTczMTk2Mjk3MX0.y69UiHYx80syBZjgIieJtrOp-ckzRS0PzQJChDwKBWw

@memberId = 1

@category_Id = 1

@gatherId = 1

@scheduleId = 4

@agreement_Id = 17a980dd-a53e-11ef-9770-00155dbf39e6


### 일반 로그인 요청
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
  "email": "nbcteam21test@gmail.com",
  "password": "skwkdrns365!A"
}

### 카테고리 생성
POST {{base_url}}/api/categories
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "categoryName": "영화"
}

### 모임 생성
POST {{base_url}}/api/gathers/{{category_Id}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "김치3",
  "description": "임치테스트",
  "hashtags": [
    "김밥",
    "김치",
    "감자"
  ],
  "addressName": "서울 동작구 노량진로 111",
  "latitude": 37.7645195812136,
  "longitude": 128.899617238918
}


###
GET http://localhost:5601/gather_document/gathering/_search
